title: ABOUT GIT
author: Kavya
email: 198606@ust.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
 GitHub, Inc. is a provider of Internet hosting for software development and version control using Git. It offers the distributed version control and source code management (SCM) functionality of Git, plus its own features. It provides access control and several collaboration features such as bug tracking, feature requests, task management, continuous integration and wikis for every project.[4] Headquartered in California, it has been a subsidiary of Microsoft since 2018.[5]
It is commonly used to host open-source projects.As of January 2020, GitHub reports having over 40 million users and more than 190 million repositories(including at least 28 million public repositories).[9] It is the largest source code host as of April 2020
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage


